<template>
  <section class="triggers-actions-panel">
    <div class="panel-heading"><div><strong>动作</strong><span>由触发器调用</span></div><div class="heading-actions"><el-button size="small" :disabled="node.nodeType === 'SUBFLOW_NODE'" @click="addAction('EMIT')">新增 EMIT</el-button><el-button size="small" @click="addAction('UPDATE')">新增 UPDATE</el-button></div></div>
    <p v-if="node.nodeType === 'SUBFLOW_NODE'" class="panel-hint">子流程节点不可新增 EMIT，以免绕过子流程执行。</p>
    <div v-for="action in actions" :key="action.actionName" class="action-card"><div class="action-card-head"><strong>{{ action.actionName || '未命名动作' }}</strong><el-icon v-if="isSystemItem(action)" title="系统动作，禁止编辑"><Lock /></el-icon><el-button v-else link type="danger" @click="removeAction(action.actionName)">删除</el-button></div><div class="form-grid"><el-input :model-value="action.actionName" placeholder="动作名称" :disabled="isSystemItem(action)" @update:model-value="updateAction(action.actionName, 'actionName', $event)" /><el-select :model-value="action.actionType" :disabled="isSystemItem(action)" @update:model-value="updateAction(action.actionName, 'actionType', $event)"><el-option label="EMIT" value="EMIT" /><el-option label="UPDATE" value="UPDATE" /></el-select><template v-if="action.actionType === 'EMIT'"><el-select :model-value="action.targetInterfaceName" placeholder="目标 OUT 接口" :disabled="isSystemItem(action)" @update:model-value="updateAction(action.actionName, 'targetInterfaceName', $event)"><el-option v-for="item in outputInterfaces" :key="item.name" :label="item.name" :value="item.name" /></el-select><el-select :model-value="action.signalName" placeholder="信号" :disabled="isSystemItem(action)" @update:model-value="updateAction(action.actionName, 'signalName', $event)"><el-option v-for="signal in allowedSignals(action.targetInterfaceName)" :key="signal" :label="signal" :value="signal" /></el-select></template><template v-else><el-select :model-value="action.internalVariableName" placeholder="内部变量" :disabled="isSystemItem(action)" @update:model-value="updateAction(action.actionName, 'internalVariableName', $event)"><el-option v-for="item in node.internalVariables || []" :key="item.name" :label="item.name" :value="item.name" /></el-select><el-input :model-value="action.valueExpression" placeholder="valueExpression" :disabled="isSystemItem(action)" @update:model-value="updateAction(action.actionName, 'valueExpression', $event)" /></template></div></div>
    <el-empty v-if="!actions.length" description="尚未定义动作" :image-size="36" />
    <div class="panel-heading trigger-heading"><div><strong>接口触发器</strong><span>仅 IN 接口可配置</span></div></div>
    <div v-for="item in inputInterfaces" :key="item.name" class="trigger-group"><div class="trigger-group-head"><strong>{{ item.name }}</strong><el-button size="small" :disabled="!actionNames.length" @click="addTrigger(item.name)">添加触发器</el-button></div><div v-for="(trigger, index) in item.bindingTriggers || []" :key="trigger._systemKey || index" class="trigger-row"><el-icon v-if="isSystemItem(trigger)" title="系统触发器，禁止编辑"><Lock /></el-icon><el-select :model-value="trigger.condition?.object" filterable allow-create default-first-option placeholder="条件对象" :disabled="isSystemItem(trigger)" @update:model-value="updateTrigger(item.name, index, 'object', $event)"><el-option v-for="object in conditionObjects" :key="object" :label="object" :value="object" /></el-select><el-select :model-value="trigger.condition?.operator" placeholder="操作符" :disabled="isSystemItem(trigger)" @update:model-value="updateTrigger(item.name, index, 'operator', $event)"><el-option v-for="operator in operators" :key="operator" :label="operator" :value="operator" /></el-select><el-input :model-value="thresholdText(trigger.condition?.threshold)" placeholder="阈值" :disabled="isSystemItem(trigger)" @update:model-value="updateTrigger(item.name, index, 'threshold', $event)" /><el-select :model-value="trigger.action" placeholder="调用动作" :disabled="isSystemItem(trigger)" @update:model-value="updateTrigger(item.name, index, 'action', $event)"><el-option v-for="name in actionNames" :key="name" :label="name" :value="name" /></el-select><el-button v-if="!isSystemItem(trigger)" link type="danger" @click="removeTrigger(item.name, index)">删除</el-button></div><el-empty v-if="!(item.bindingTriggers || []).length" description="尚未定义触发器" :image-size="30" /></div>
  </section>
</template>
<script setup lang="ts">
import { computed } from 'vue'
import { Lock } from '@element-plus/icons-vue'
import { isSystemItem, removeAction as removeNodeAction } from '../../../utils/workflowNodeDefinition.js'
type Item = Record<string, any>
const props = defineProps<{ node: Item }>()
const emit = defineEmits<{ 'update:node': [node: Item] }>()
const operators = ['>', '<', '>=', '<=', '=', '!=', 'BETWEEN', 'IN']
const actions = computed(() => props.node.actions || [])
const outputInterfaces = computed(() => (props.node.interfaces || []).filter((item: Item) => item.direction === 'OUT'))
const inputInterfaces = computed(() => (props.node.interfaces || []).filter((item: Item) => item.direction === 'IN'))
const actionNames = computed(() => actions.value.map((item: Item) => item.actionName).filter(Boolean))
const conditionObjects = computed(() => ['inputSignalName', 'inputPayload.stateName', 'nodeLifecycleState', 'expression', ...(props.node.internalVariables || []).map((item: Item) => item.name)])
function publish(next: Item) { emit('update:node', next) }
function allowedSignals(interfaceName: string) { return outputInterfaces.value.find((item: Item) => item.name === interfaceName)?.allowedSignals || [] }
function uniqueActionName(prefix: string) { let index = 1; while (actionNames.value.includes(`${prefix}${index}`)) index += 1; return `${prefix}${index}` }
function addAction(actionType: 'EMIT' | 'UPDATE') { if (actionType === 'EMIT' && props.node.nodeType === 'SUBFLOW_NODE') return; const target = outputInterfaces.value[0]; const action = actionType === 'EMIT' ? { actionName: uniqueActionName('emit'), actionType, targetInterfaceName: target?.name || '', signalName: target?.allowedSignals?.[0] || '' } : { actionName: uniqueActionName('update'), actionType, internalVariableName: props.node.internalVariables?.[0]?.name || '', valueExpression: '' }; publish({ ...props.node, actions: [...actions.value, action] }) }
function updateAction(actionName: string, field: string, value: any) { if (field === 'actionName' && actions.value.some((item: Item) => item.actionName === value && item.actionName !== actionName)) return; const nextActions = actions.value.map((item: Item) => item.actionName === actionName ? { ...item, [field]: value } : item); if (field === 'actionType') { const edited = nextActions.find((item: Item) => item.actionName === actionName); if (edited) Object.assign(edited, value === 'EMIT' ? { targetInterfaceName: outputInterfaces.value[0]?.name || '', signalName: outputInterfaces.value[0]?.allowedSignals?.[0] || '' } : { internalVariableName: props.node.internalVariables?.[0]?.name || '', valueExpression: '' }) }; publish({ ...props.node, actions: nextActions }) }
function removeAction(actionName: string) { try { publish(removeNodeAction(props.node, actionName)) } catch {} }
function addTrigger(interfaceName: string) { const interfaces = (props.node.interfaces || []).map((item: Item) => item.name === interfaceName ? { ...item, bindingTriggers: [...(item.bindingTriggers || []), { condition: { object: 'inputSignalName', operator: '=', threshold: '' }, action: actionNames.value[0] || '' }] } : item); publish({ ...props.node, interfaces }) }
function updateTrigger(interfaceName: string, index: number, field: string, value: any) { const interfaces = (props.node.interfaces || []).map((item: Item) => { if (item.name !== interfaceName) return item; const bindingTriggers = (item.bindingTriggers || []).map((trigger: Item, triggerIndex: number) => triggerIndex !== index ? trigger : field === 'action' ? { ...trigger, action: value } : { ...trigger, condition: { ...trigger.condition, [field]: value } }); return { ...item, bindingTriggers } }); publish({ ...props.node, interfaces }) }
function removeTrigger(interfaceName: string, index: number) { const interfaces = (props.node.interfaces || []).map((item: Item) => item.name === interfaceName ? { ...item, bindingTriggers: (item.bindingTriggers || []).filter((_trigger: Item, triggerIndex: number) => triggerIndex !== index) } : item); publish({ ...props.node, interfaces }) }
function thresholdText(value: unknown) { return Array.isArray(value) ? value.join(', ') : value == null ? '' : String(value) }
</script>
<style scoped>
.triggers-actions-panel{display:grid;gap:10px}.panel-heading,.trigger-group-head,.action-card-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.panel-heading>div:first-child{display:grid;gap:2px}.panel-heading span,.panel-hint{margin:0;color:var(--el-text-color-secondary);font-size:12px}.heading-actions{display:flex;gap:6px}.action-card,.trigger-group{display:grid;gap:8px;padding:10px;border:1px solid var(--el-border-color-lighter);border-radius:7px}.action-card-head{font-size:13px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.form-grid :deep(.el-select),.trigger-row :deep(.el-select){width:100%}.trigger-heading{margin-top:12px;padding-top:14px;border-top:1px solid var(--el-border-color-lighter)}.trigger-row{display:grid;grid-template-columns:auto minmax(110px,1.2fr) 78px minmax(92px,1fr) minmax(100px,1fr) auto;gap:7px;align-items:center}.trigger-row .el-icon{color:var(--el-text-color-secondary)}@media(max-width:560px){.form-grid,.trigger-row{grid-template-columns:1fr 1fr}.trigger-row .el-icon{display:none}}
</style>
