from pathlib import Path
p=Path(r'D:\SmartLab2.0\doc\_tmp\translation_v5\build.mjs')
s=p.read_text(encoding='utf-8')
s=s.replace("    'Laboratories already automate task workflows.':'With the rise of large language models, smart chemical laboratories are evolving from automated task execution toward',", "    'Laboratories already automate task workflows.':'With the rise of large language models, smart chemical laboratories are evolving from automated task execution toward',\n    'Laboratories already automate task workflows.\\nLarge language models (LLMs) now also contribute to planning and device control.':'With the rise of large language models, smart chemical laboratories are evolving from automated task execution toward\\nLLM-assisted decision-making and control.',")
s=s.replace("    'LLM device control requires explicit limits:':'With LLMs in the loop, execution boundaries become more important:',", "    'LLM device control requires explicit limits:':'With LLMs in the loop, execution boundaries become more important:',\n    'LLM device control requires explicit limits:\\nWhich operations may an LLM request, and when are they allowed?':'With LLMs in the loop, execution boundaries become more important:\\nWhat requests may an LLM make, and under what conditions may those requests be executed?',")
s=s.replace("    'Attributes and operationsParameters and interfacesAdapter mapping contractIntrinsic constraints':'Device attributes, capabilities, and parameters\\nInterfaces and Adapter mapping contract\\nIntrinsic constraints',", "    'Attributes and operationsParameters and interfacesAdapter mapping contractIntrinsic constraints':'Device attributes, capabilities, and parameters\\nInterfaces and Adapter mapping contract\\nIntrinsic constraints',\n    'Attributes and operations\\nParameters and interfaces\\nAdapter mapping contract\\nIntrinsic constraints':'Device attributes, capabilities, and parameters\\nInterfaces and Adapter mapping contract\\nIntrinsic constraints',")
s=s.replace("    'Check requests and stateRun transition actionsUpdate state on feedback':'Handle requests and check state\\nState transitions and command output\\nUpdate state from feedback',", "    'Check requests and stateRun transition actionsUpdate state on feedback':'Handle requests and check state\\nState transitions and command output\\nUpdate state from feedback',\n    'Check requests and state\\nRun transition actions\\nUpdate state on feedback':'Handle requests and check state\\nState transitions and command output\\nUpdate state from feedback',")
s=s.replace("    'Standard control command':'Upper-level command',", "    'Standard control command':'Upper-level command',\n    'Start\\nsignal':'Start signal',\n    'Control\\ncommand':'Control request',")
p.write_text(s,encoding='utf-8')
