<template>
  <div class="security-page">
    <header class="page-heading"><div><h1>约束管理</h1><p>管理跨任务或长期生效的全局约束；任务专属约束请在创建任务时配置</p></div><div><el-button :icon="Refresh" @click="load">刷新</el-button><el-button v-if="canCreate" type="primary" :icon="Plus" @click="open()">新建约束规则</el-button></div></header>
    <el-card shadow="never"><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="搜索名称或说明" @keyup.enter="load"/><el-select v-model="query.isEnabled" clearable placeholder="启用状态"><el-option label="启用" :value="true"/><el-option label="停用" :value="false"/></el-select><el-button type="primary" @click="load">查询</el-button></div>
      <el-table :data="items" v-loading="loading" border stripe size="small"><el-table-column prop="id" label="ID" width="70"/><el-table-column prop="ruleName" label="约束名称" min-width="170"/><el-table-column prop="expression" label="违规表达式" min-width="230" show-overflow-tooltip/><el-table-column label="变量" width="70"><template #default="{row}">{{ Object.keys(row.bindings || {}).length }}</template></el-table-column><el-table-column label="动作" width="70"><template #default="{row}">{{ (row.violationActions || []).length }}</template></el-table-column><el-table-column prop="description" label="说明" min-width="160" show-overflow-tooltip/><el-table-column label="状态" width="85"><template #default="{row}"><el-switch v-model="row.isEnabled" :disabled="!canEdit" size="small" @change="value => setEnabled(row,Boolean(value))"/></template></el-table-column><el-table-column label="操作" width="140" fixed="right"><template #default="{row}"><el-button v-if="canEdit" link type="primary" @click="open(row)">编辑</el-button><el-popconfirm v-if="canDelete" title="确认删除该规则？" @confirm="remove(row)"><template #reference><el-button link type="danger">删除</el-button></template></el-popconfirm></template></el-table-column></el-table>
      <div class="pager"><el-pagination v-model:current-page="query.pageNo" v-model:page-size="query.pageSize" :total="total" layout="total,sizes,prev,pager,next" @current-change="load" @size-change="load"/></div>
    </el-card>
    <el-dialog v-model="visible" :title="editingId ? '编辑约束规则' : '新建约束规则'" width="1040px" destroy-on-close @opened="loadEditor"><ConstraintRuleEditor ref="editorRef" :models="models" :instances="instances" :workflows="workflows" :tasks="tasks" :source-types="sourceTypes" :system-actions="systemActions"/><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue'
import axios from 'axios'
import { ElMessage } from 'element-plus'
import { Plus,Refresh } from '@element-plus/icons-vue'
import { useAuthStore } from '../../stores/authStore'
import ConstraintRuleEditor from '../../components/constraint/ConstraintRuleEditor.vue'
const auth=useAuthStore(),canCreate=computed(()=>auth.hasPermission('constraint_rule:create')),canEdit=computed(()=>auth.hasPermission('constraint_rule:edit')),canDelete=computed(()=>auth.hasPermission('constraint_rule:delete'))
const loading=ref(false),saving=ref(false),visible=ref(false),items=ref<any[]>([]),total=ref(0),editingId=ref<number|null>(null),editingRule=ref<any>(null),editorRef=ref<any>(),models=ref<any[]>([]),instances=ref<any[]>([]),workflows=ref<any[]>([]),tasks=ref<any[]>([]),sourceTypes=ref<string[]>([]),systemActions=ref<string[]>([])
const query=reactive({pageNo:1,pageSize:20,keyword:'',isEnabled:undefined as boolean|undefined})
async function refs(){const [o,m,i,w,t]=await Promise.all([axios.get('/api/constraint/rule/options'),axios.get('/api/device/model/list'),axios.get('/api/device/instance/list'),axios.get('/api/workflow/list'),axios.get('/api/task/page',{params:{pageNo:1,pageSize:500}})]);if(o.data?.success){sourceTypes.value=o.data.data.observableSourceTypes||[];systemActions.value=o.data.data.systemViolationActions||[]}if(m.data?.success)models.value=m.data.data||[];if(i.data?.success)instances.value=i.data.data||[];if(t.data?.success)tasks.value=t.data.data?.records||[];if(w.data?.success){const summaries=w.data.data||[];workflows.value=(await Promise.all(summaries.map(async(flow:any)=>{try{const detail=await axios.get('/api/workflow/detail/'+flow.id);return detail.data?.success?{...flow,...detail.data.data}:flow}catch{return flow}})))}}
async function load(){loading.value=true;try{const res=await axios.get('/api/constraint/rule/page',{params:query});if(!res.data?.success)throw Error(res.data?.message||'加载失败');items.value=res.data.data?.records||[];total.value=res.data.data?.total||0}catch(e:any){ElMessage.error(e.message||'加载约束规则失败')}finally{loading.value=false}}
async function open(row?:any){editingId.value=row?.id||null;editingRule.value=row||null;await refs();visible.value=true}function loadEditor(){editorRef.value?.loadRule(editingRule.value)}
async function save(){try{const rule=editorRef.value?.validateAndBuild();if(!rule)return;const payload={...rule,id:editingId.value};saving.value=true;const res=editingId.value?await axios.put('/api/constraint/rule/'+editingId.value,payload):await axios.post('/api/constraint/rule',payload);if(!res.data?.success)throw Error(res.data?.message||'保存失败');ElMessage.success('约束规则已保存');visible.value=false;load()}catch(e:any){ElMessage.error(e.message||'保存约束规则失败')}finally{saving.value=false}}
async function setEnabled(row:any,value:boolean){try{const res=await axios.patch('/api/constraint/rule/'+row.id+'/enabled',null,{params:{enabled:value}});if(!res.data?.success)throw Error(res.data?.message||'更新失败')}catch(e:any){row.isEnabled=!value;ElMessage.error(e.message||'更新失败')}}async function remove(row:any){try{const res=await axios.delete('/api/constraint/rule/'+row.id);if(!res.data?.success)throw Error(res.data?.message||'删除失败');ElMessage.success('约束规则已删除');load()}catch(e:any){ElMessage.error(e.message||'删除失败')}}
onMounted(()=>{load();refs().catch((e:any)=>ElMessage.error(e.message||'加载约束配置资源失败'))})
</script>
<style scoped>
.security-page{padding:20px}.page-heading,.toolbar{display:flex;align-items:center;gap:10px}.page-heading{justify-content:space-between;margin-bottom:16px}.page-heading h1{margin:0;font-size:22px}.page-heading p{margin:6px 0 0;color:#64748b;font-size:13px}.toolbar{margin-bottom:14px}.toolbar .el-input{width:320px}.toolbar .el-select{width:120px}.pager{display:flex;justify-content:flex-end;margin-top:16px}
</style>
