<template>
  <el-drawer :model-value="modelValue" :title="`任务详情 · ${task?.taskName || ''}`" size="78%" class="unified-workflow-drawer" @update:model-value="emit('update:modelValue', $event)">
    <div v-if="task" class="execution-drawer" v-loading="loading">
      <header class="execution-header"><div><strong>{{ task.taskName }}</strong><span>任务 #{{ task.id }} · {{ workflow?.flowName || `流程 ${task.flowModelId}` }}</span></div><div><el-button @click="emit('refresh')">刷新</el-button><el-button v-if="task.taskStatus === 'RUNNING'" type="warning" plain @click="emit('terminate')">终止任务</el-button><el-tag :type="statusType(task.taskStatus)" effect="dark" size="large">{{ statusLabel(task.taskStatus) }}</el-tag></div></header>
      <el-tabs v-model="activeTab" class="execution-tabs">
        <el-tab-pane label="运行概览" name="overview">
          <div class="overview-grid"><div><span>执行状态</span><strong>{{ statusLabel(task.taskStatus) }}</strong></div><div><span>执行步骤</span><strong>{{ steps.length }}</strong></div><div><span>设备绑定</span><strong>{{ bindings.length }}</strong></div><div><span>开始时间</span><strong>{{ formatTime(task.startTime) }}</strong></div></div>
          <el-descriptions :column="2" border size="small"><el-descriptions-item label="流程名称">{{ workflow?.flowName || '-' }}</el-descriptions-item><el-descriptions-item label="当前节点">{{ task.currentNodeIdRef == null ? '-' : task.currentNodeIdRef }}</el-descriptions-item><el-descriptions-item label="开始时间">{{ formatTime(task.startTime) }}</el-descriptions-item><el-descriptions-item label="结束时间">{{ formatTime(task.endTime) }}</el-descriptions-item></el-descriptions>
        </el-tab-pane>
        <el-tab-pane label="执行流程图" name="graph"><div class="graph-layout"><TaskRuntimeGraph :workflow="workflow" :steps="steps" :selected-step-id="selectedStepId" @select-step="selectGraphStep"/><div class="graph-detail"><TaskStepDetail v-if="selectedStep" :step="selectedStep"/><div v-else-if="selectedGraphNode" class="waiting-detail"><strong>{{ selectedGraphNode.name }}</strong><el-tag type="info" effect="plain">WAITING</el-tag><span>{{ nodeTypeLabel(selectedGraphNode) }}</span><p>尚未创建执行步骤</p></div><el-empty v-else description="选择流程节点查看详情" :image-size="44"/></div></div></el-tab-pane>
        <el-tab-pane label="步骤详情" name="steps"><div class="step-layout"><TaskStepTree :steps="steps" :selected-id="selectedStepId" @select="selectStep"/><TaskStepDetail :step="selectedStep" /></div></el-tab-pane>
        <el-tab-pane label="设备绑定" name="bindings"><div class="binding-list"><div v-for="binding in bindings" :key="binding.bindingKey || binding.nodeName" class="binding-row"><div><strong>{{ binding.nodeName }}</strong><span>{{ binding.flowName }} · {{ binding.deviceModelName || binding.deviceModelId }}</span></div><span>→</span><div><strong>{{ binding.instanceName || binding.deviceInstanceName || binding.deviceInstanceId || '待绑定' }}</strong><span>设备实例</span></div></div><el-empty v-if="!bindings.length" description="该任务没有设备实例绑定" :image-size="44" /></div></el-tab-pane>
        <el-tab-pane label="任务约束" name="constraints"><div class="constraint-view"><el-alert type="info" :closable="false" title="全局约束实时生效；任务级约束在任务启动后保持固定。"/><template v-if="constraints"><section><h4>全局约束 · 实时</h4><div v-for="rule in constraints.globalConstraints || []" :key="rule.ruleId" class="rule-row"><strong>{{ rule.ruleName }}</strong><code>{{ rule.expression }}</code></div><el-empty v-if="!constraints.globalConstraints?.length" description="当前没有启用的全局约束" :image-size="36"/></section><section><h4>任务约束 · 固定</h4><div v-for="rule in constraints.taskConstraints || []" :key="rule.taskRuleIndex" class="rule-row"><strong>{{ rule.ruleName }}</strong><code>{{ rule.expression }}</code></div><el-empty v-if="!constraints.taskConstraints?.length" description="该任务未配置任务约束" :image-size="36"/></section></template><el-empty v-else description="暂无有效约束模型" :image-size="44" /></div></el-tab-pane>
        <el-tab-pane label="业务事件" name="events"><TaskBusinessEventList :logs="logs" /></el-tab-pane>
      </el-tabs>
    </div>
  </el-drawer>
</template>
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import TaskBusinessEventList from './TaskBusinessEventList.vue'
import TaskRuntimeGraph from './TaskRuntimeGraph.vue'
import TaskStepDetail from './TaskStepDetail.vue'
import TaskStepTree from './TaskStepTree.vue'
type Item=Record<string,any>
const props=withDefaults(defineProps<{ modelValue:boolean, task?:Item|null, workflow?:Item|null, steps?:Item[], logs?:Item[], bindings?:Item[], constraints?:Item|null, loading?:boolean }>(),{task:null,workflow:null,steps:()=>[],logs:()=>[],bindings:()=>[],constraints:null,loading:false})
const emit=defineEmits<{ 'update:modelValue':[value:boolean], refresh:[], terminate:[], 'select-step':[stepId:number|null] }>()
const activeTab=ref('overview')
const selectedStepId=ref<number|null>(null)
const selectedGraphNode=ref<Item|null>(null)
const selectedStep=computed(()=>props.steps.find(step=>step.id===selectedStepId.value)||null)
watch(()=>props.steps,current=>{if(!current.some(step=>step.id===selectedStepId.value))selectedStepId.value=current[0]?.id??null},{immediate:true})
function selectStep(step:Item){selectedStepId.value=step.id;emit('select-step',step.id)}
function selectGraphStep(stepId:number|null,node:Item){selectedStepId.value=stepId;selectedGraphNode.value=node;emit('select-step',stepId)}
function nodeTypeLabel(node:Item){if(node.nodeType==='DEV_NODE')return '设备能力节点';if(node.nodeType==='SUBFLOW_NODE')return '子流程节点';return '功能节点'}
function statusType(status:string){return ({PENDING:'info',RUNNING:'primary',SUCCEEDED:'success',FAILED:'danger',TERMINATING:'warning',TERMINATED:'warning'} as Record<string,string>)[status]||'info'}
function statusLabel(status:string){return ({PENDING:'排队中',RUNNING:'运行中',SUCCEEDED:'已完成',FAILED:'失败',TERMINATING:'终止中',TERMINATED:'已终止'} as Record<string,string>)[status]||status}
function formatTime(value:unknown){if(!value)return '-';const date=new Date(value as any);return Number.isNaN(date.getTime())?String(value):date.toLocaleString('zh-CN',{hour12:false})}
</script>
<style scoped>
.execution-drawer{display:grid;gap:12px;min-height:400px}.execution-header{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:12px 14px;border:1px solid #e1e6ec;background:#f7f9fb}.execution-header>div:first-child{display:grid;gap:3px}.execution-header>div:last-child{display:flex;align-items:center;gap:8px}.execution-header strong{font-size:15px}.execution-header span{color:#7f8b9b;font-size:10px}.execution-tabs :deep(.el-tabs__header){margin-bottom:12px}.overview-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));margin-bottom:12px;border:1px solid #e2e7ed}.overview-grid>div{display:grid;gap:4px;padding:12px;border-right:1px solid #e2e7ed}.overview-grid>div:last-child{border-right:0}.overview-grid span{color:#7d8999;font-size:10px}.overview-grid strong{font-size:15px}.step-layout{display:grid;grid-template-columns:260px minmax(0,1fr);gap:12px}.step-layout>:first-child{max-height:620px;overflow:auto;padding-right:4px}.graph-layout{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:12px}.graph-detail{max-height:520px;overflow:auto;padding:10px;border:1px solid #e1e6ec}.waiting-detail{display:grid;grid-template-columns:1fr auto;gap:8px;padding:12px;border:1px solid #e2e7ed;background:#f8fafc}.waiting-detail span,.waiting-detail p{grid-column:1/-1;margin:0;color:#7b8898;font-size:10px}.binding-list,.constraint-view{display:grid;gap:9px}.binding-row{display:grid;grid-template-columns:minmax(0,1fr) 24px minmax(0,1fr);align-items:center;gap:10px;padding:10px 12px;border:1px solid #e1e6ec}.binding-row>div{display:grid;gap:2px}.binding-row strong{font-size:11px}.binding-row span{color:#7c899a;font-size:10px}.constraint-view section{display:grid;gap:7px}.constraint-view h4{margin:8px 0 0;font-size:12px}.rule-row{display:grid;grid-template-columns:180px minmax(0,1fr);gap:10px;padding:9px 11px;border:1px solid #e4e8ed;background:#fafbfc}.rule-row strong{font-size:11px}.rule-row code{color:#48617e;font-size:10px}@media(max-width:1100px){.graph-layout{grid-template-columns:1fr}.graph-detail{max-height:none}}@media(max-width:900px){.overview-grid{grid-template-columns:repeat(2,1fr)}.step-layout{grid-template-columns:1fr}.execution-header{align-items:flex-start;flex-direction:column}}
</style>
