<template>
  <div class="constraint-editor">
    <el-row :gutter="14">
      <el-col :span="16"><el-form-item label="规则名称" required><el-input v-model="form.ruleName" placeholder="请输入可识别的约束名称" /></el-form-item></el-col>
      <el-col :span="8"><el-form-item label="启用"><el-switch v-model="form.isEnabled" /></el-form-item></el-col>
    </el-row>
    <el-form-item label="规则说明"><el-input v-model="form.description" type="textarea" :rows="2" /></el-form-item>

    <section class="editor-block formula-block">
      <div class="block-head"><div><strong>1.违规表达式</strong><span>变量名前使用@，变量绑定会与表达式自动同步</span></div>
        <el-popover placement="right-start" :width="520" trigger="click">
          <template #reference><el-button class="btn-aliyun">插入公式模板</el-button></template>
          <div class="formula-panel"><div class="formula-panel-title">选择表达式模板</div><button v-for="item in templates" :key="item.key" type="button" @click="selectTemplate(item.expression)"><strong>{{ item.name }}</strong><code>{{ item.expression }}</code><span>{{ item.description }}</span></button></div>
        </el-popover>
      </div>
      <el-input v-model="form.displayExpression" class="formula-input" placeholder="例如：@temperature > @limit" clearable />
      <div class="formula-help">后端表达式预览：<code>{{ backendExpression || '-' }}</code></div>
    </section>

    <section class="editor-block">
      <div class="block-head"><div><strong>2.变量绑定</strong><span>以下变量由表达式中的@引用自动生成，不需要手写bindings JSON</span></div></div>
      <el-empty v-if="!form.bindings.length" description="请先插入公式或在表达式中输入@变量" :image-size="54" />
      <div v-for="item in form.bindings" :key="item.name" class="entry">
        <div class="entry-title"><code>@{{ item.name }}</code><el-radio-group v-model="item.bindingType" size="small"><el-radio-button value="OBSERVABLE">观测数据</el-radio-button><el-radio-button value="LITERAL">固定值</el-radio-button></el-radio-group></div>
        <el-row v-if="item.bindingType === 'LITERAL'" :gutter="12">
          <el-col :span="8"><el-form-item label="数据类型"><el-select v-model="item.dataType"><el-option v-for="type in scalarTypes" :key="type" :label="type" :value="type" /></el-select></el-form-item></el-col>
          <el-col :span="12"><el-form-item label="固定值"><el-select v-if="item.dataType === 'BOOLEAN'" v-model="item.value"><el-option label="true" :value="true" /><el-option label="false" :value="false" /></el-select><el-input-number v-else-if="isNumeric(item.dataType)" v-model="item.value" :controls="false" /><el-input v-else v-model="item.value" /></el-form-item></el-col>
        </el-row>
        <template v-else>
          <el-row :gutter="12"><el-col :span="8"><el-form-item label="观测来源"><el-select v-model="item.sourceType" @change="resetSource(item)"><el-option v-for="type in sourceTypes" :key="type" :label="sourceLabel(type)" :value="type" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="数据类型"><el-input :model-value="observableDataType(item)" disabled /></el-form-item></el-col></el-row>
          <el-row v-if="isDeviceSource(item.sourceType)" :gutter="12">
            <template v-if="taskMode"><el-col :span="12"><el-form-item label="任务设备"><el-select v-model="item.resourceKey" @change="selectTaskResource(item)"><el-option v-for="resource in taskResources" :key="resource.bindingKey" :label="resourceLabel(resource)" :value="resource.bindingKey" /></el-select></el-form-item></el-col></template>
            <template v-else><el-col :span="7"><el-form-item label="设备模型"><el-select v-model="item.deviceModelId" filterable @change="resetDevice(item)"><el-option v-for="model in models" :key="model.id" :label="model.modelName" :value="model.id" /></el-select></el-form-item></el-col><el-col :span="7"><el-form-item label="设备实例"><el-select v-model="item.deviceInstanceId" clearable placeholder="不选表示模型全部实例"><el-option v-for="instance in instancesFor(item.deviceModelId)" :key="instance.id" :label="instance.instanceName || instance.id" :value="instance.id" /></el-select></el-form-item></el-col></template>
            <el-col v-if="item.sourceType === 'DEVICE_ATTRIBUTE'" :span="8"><el-form-item label="设备属性"><el-select v-model="item.targetName" filterable><el-option v-for="attr in attributesFor(item.deviceModelId)" :key="attr.attributeName" :label="attr.displayName || attr.attributeName" :value="attr.attributeName" /></el-select></el-form-item></el-col>
            <el-col v-if="item.sourceType === 'DEVICE_OPERATION_STATE'" :span="8"><el-form-item label="OP状态空间"><el-select v-model="item.regionName"><el-option v-for="region in operationRegions(item.deviceModelId)" :key="region.regionName" :label="region.regionName" :value="region.regionName" /></el-select></el-form-item></el-col>
          </el-row>
          <el-row v-if="isNodeSource(item.sourceType)" :gutter="12"><el-col :span="8"><el-form-item label="工作流"><el-select v-model="item.workflowTemplateId" @change="item.nodeName='';item.variableName=''"> <el-option v-for="flow in availableWorkflows" :key="flow.id" :label="flow.flowName" :value="flow.id" /></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="节点"><el-select v-model="item.nodeName" filterable @change="item.variableName=''"><el-option v-for="node in nodesFor(item.workflowTemplateId)" :key="node.name" :label="node.name" :value="node.name" /></el-select></el-form-item></el-col><el-col v-if="item.sourceType === 'NODE_INTERNAL_VARIABLE'" :span="8"><el-form-item label="内部变量"><el-select v-model="item.variableName" filterable><el-option v-for="variable in internalVariablesFor(item)" :key="variable.name" :label="variable.name + ' · ' + variable.dataType" :value="variable.name" /></el-select></el-form-item></el-col></el-row>
          <el-alert v-if="item.sourceType === 'TASK_LIFECYCLE_STATE' && taskMode" type="info" :closable="false" title="该变量自动绑定当前任务的TASK_STATUS" />
          <el-row v-else-if="item.sourceType === 'TASK_LIFECYCLE_STATE'"><el-col :span="10"><el-form-item label="目标任务"><el-select v-model="item.taskId" filterable><el-option v-for="task in tasks" :key="task.id" :label="(task.taskName || '任务') + '#' + task.id" :value="task.id" /></el-select></el-form-item></el-col></el-row>
        </template>
      </div>
    </section>

    <section class="editor-block">
      <div class="block-head"><div><strong>3.违规动作</strong><span>动作通过表单生成，设备能力按模型→实例→能力选择</span></div><el-button class="btn-aliyun" size="small" @click="addAction">添加动作</el-button></div>
      <div v-for="(item,index) in form.actions" :key="item.key" class="entry"><div class="entry-title"><strong>动作{{ index + 1 }}</strong><el-button class="btn-aliyun-danger-link" link @click="form.actions.splice(index,1)">删除</el-button></div>
        <el-radio-group v-model="item.actionType" @change="resetAction(item)"><el-radio value="SYSTEM">系统处置</el-radio><el-radio value="DEVICE_CAPABILITY">设备能力</el-radio></el-radio-group>
        <el-row v-if="item.actionType === 'SYSTEM'" :gutter="12"><el-col :span="8"><el-form-item label="系统动作"><el-select v-model="item.action"><el-option v-for="name in systemActions" :key="name" :label="name" :value="name" /></el-select></el-form-item></el-col><el-col v-if="!taskMode && item.action !== 'ALERT'" :span="10"><el-form-item label="目标任务"><el-select v-model="item.targetTaskId"><el-option v-for="task in tasks" :key="task.id" :label="(task.taskName || '任务') + '#' + task.id" :value="task.id" /></el-select></el-form-item></el-col><el-col v-if="taskMode" :span="12"><el-alert type="info" :closable="false" title="系统动作自动作用于当前任务" /></el-col></el-row>
        <el-row v-else :gutter="12"><template v-if="taskMode"><el-col :span="8"><el-form-item label="任务设备"><el-select v-model="item.resourceKey" @change="selectActionResource(item)"><el-option v-for="resource in taskResources" :key="resource.bindingKey" :label="resourceLabel(resource)" :value="resource.bindingKey" /></el-select></el-form-item></el-col></template><template v-else><el-col :span="7"><el-form-item label="设备模型"><el-select v-model="item.deviceModelId" @change="resetActionDevice(item)"><el-option v-for="model in models" :key="model.id" :label="model.modelName" :value="model.id" /></el-select></el-form-item></el-col><el-col :span="7"><el-form-item label="设备实例"><el-select v-model="item.deviceInstanceId" @change="item.capabilityName=''"> <el-option v-for="instance in instancesFor(item.deviceModelId)" :key="instance.id" :label="instance.instanceName || instance.id" :value="instance.id" /></el-select></el-form-item></el-col></template><el-col :span="8"><el-form-item label="设备能力"><el-select v-model="item.capabilityName" @change="initParameters(item)"><el-option v-for="capability in capabilitiesFor(item.deviceModelId)" :key="capability.capabilityName" :label="capability.capabilityName" :value="capability.capabilityName" /></el-select></el-form-item></el-col></el-row>
        <el-row v-if="parameterDefinitions(item).length" :gutter="12"><el-col v-for="parameter in parameterDefinitions(item)" :key="parameter.name" :span="8"><el-form-item :label="parameter.name"><el-select v-if="parameter.dataType === 'BOOLEAN'" v-model="item.parameters[parameter.name]"><el-option label="true" :value="true" /><el-option label="false" :value="false" /></el-select><el-input-number v-else-if="isNumeric(parameter.dataType)" v-model="item.parameters[parameter.name]" :controls="false" /><el-input v-else v-model="item.parameters[parameter.name]" /></el-form-item></el-col></el-row>
      </div>
    </section>
    <el-form-item label="持续触发阈值"><el-input-number v-model="form.windowSeconds" :controls="false" :min="1" placeholder="空表示瞬时触发" /><span class="inline-hint">秒，表达式连续为true达到该时长后违规</span></el-form-item>
  </div>
</template>

<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import { extractExpressionVariables, toBackendExpression, validateDisplayExpressionSyntax } from '../../utils/constraintExpression.js'

const props = withDefaults(defineProps<{ models:any[],instances:any[],workflows:any[],tasks:any[],taskMode?:boolean,taskResources?:any[],taskWorkflowNodes?:any[],sourceTypes?:string[],systemActions?:string[] }>(), { taskMode:false,taskResources:()=>[],taskWorkflowNodes:()=>[],sourceTypes:()=>['DEVICE_ATTRIBUTE','DEVICE_OPERATION_STATE','DEVICE_COMMAND_LIFECYCLE','NODE_LIFECYCLE_STATE','NODE_INTERNAL_VARIABLE','TASK_LIFECYCLE_STATE'],systemActions:()=>['ABORT','PAUSE','ALERT'] })
const templates=[{key:'COMPARE',name:'阈值比较',expression:'@observedValue > @threshold',description:'数值超过或低于阈值'},{key:'NOT_EQUAL',name:'不等判断',expression:'@actual != @expected',description:'状态或值与期望不一致'},{key:'RANGE',name:'越界判断',expression:'@value < @minimum || @value > @maximum',description:'数值超出允许区间'},{key:'BOOLEAN',name:'布尔条件',expression:'@flag == true',description:'故障位或开关条件为真'},{key:'AVERAGE',name:'窗口平均值',expression:'avg(@value, 60) > @threshold',description:'最近60秒平均值越界'}]
const scalarTypes=['INTEGER','DOUBLE','STRING','BOOLEAN']; let serial=0
const newBinding=(name:string)=>({name,bindingType:/threshold|minimum|maximum|expected/i.test(name)?'LITERAL':'OBSERVABLE',dataType:'DOUBLE',value:0,sourceType:'DEVICE_ATTRIBUTE',resourceKey:'',deviceModelId:null,deviceInstanceId:null,targetName:'',regionName:'',workflowTemplateId:null,nodeName:'',variableName:'',taskId:null})
const newAction=()=>({key:++serial,actionType:'SYSTEM',action:'ALERT',targetTaskId:null,resourceKey:'',deviceModelId:null,deviceInstanceId:null,capabilityName:'',parameters:{} as Record<string,any>})
const form=reactive<any>({ruleName:'',description:'',isEnabled:true,displayExpression:'',bindings:[],actions:[newAction()],windowSeconds:null})
const backendExpression=computed(()=>toBackendExpression(form.displayExpression))
const availableWorkflows=computed(()=>props.taskMode?[...new Map(props.taskWorkflowNodes.map((x:any)=>[Number(x.flowModelId),{id:Number(x.flowModelId),flowName:x.flowName||('流程'+x.flowModelId)}])).values()]:props.workflows)
watch(()=>form.displayExpression,()=>syncBindings())
function variableNames(){return extractExpressionVariables(form.displayExpression)}
function syncBindings(){const existing=new Map(form.bindings.map((x:any)=>[x.name,x]));form.bindings=variableNames().map(name=>existing.get(name)||newBinding(name))}
function selectTemplate(expression:string){form.displayExpression=expression}
const isNumeric=(type:string)=>type==='INTEGER'||type==='DOUBLE',isDeviceSource=(type:string)=>['DEVICE_ATTRIBUTE','DEVICE_OPERATION_STATE','DEVICE_COMMAND_LIFECYCLE'].includes(type),isNodeSource=(type:string)=>['NODE_LIFECYCLE_STATE','NODE_INTERNAL_VARIABLE'].includes(type)
const sourceLabel=(type:string)=>({DEVICE_ATTRIBUTE:'设备属性',DEVICE_OPERATION_STATE:'设备运行状态',DEVICE_COMMAND_LIFECYCLE:'设备命令生命周期',NODE_LIFECYCLE_STATE:'节点生命周期',NODE_INTERNAL_VARIABLE:'节点内部变量',TASK_LIFECYCLE_STATE:'任务生命周期'} as any)[type]||type
const model=(id:any)=>props.models.find((x:any)=>Number(x.id||x.modelId)===Number(id)),instancesFor=(id:any)=>props.instances.filter((x:any)=>Number(x.deviceModelId||x.modelId)===Number(id)),attributesFor=(id:any)=>Array.isArray(model(id)?.attributes)?model(id).attributes:[],capabilitiesFor=(id:any)=>Array.isArray(model(id)?.capabilities)?model(id).capabilities:[],operationRegions=(id:any)=>Array.isArray(model(id)?.opState?.regions)?model(id).opState.regions:[]
function internalVariablesFor(item:any){return nodesFor(item.workflowTemplateId).find((node:any)=>node.name===item.nodeName)?.internalVariables||[]}
function observableDataType(item:any){if(item.sourceType==='DEVICE_ATTRIBUTE')return attributesFor(item.deviceModelId).find((x:any)=>x.attributeName===item.targetName)?.dataType||'待选择属性';if(item.sourceType==='NODE_INTERNAL_VARIABLE')return internalVariablesFor(item).find((variable:any)=>variable.name===item.variableName)?.dataType||'待选择内部变量';return 'STRING'}
function resetSource(item:any){Object.assign(item,{resourceKey:'',deviceModelId:null,deviceInstanceId:null,targetName:'',regionName:'',workflowTemplateId:props.taskMode&&availableWorkflows.value.length===1?availableWorkflows.value[0].id:null,nodeName:'',variableName:'',taskId:null})}
function resetDevice(item:any){Object.assign(item,{deviceInstanceId:null,targetName:'',regionName:''})}
function selectTaskResource(item:any){const resource=props.taskResources.find((x:any)=>x.bindingKey===item.resourceKey);if(resource)Object.assign(item,{deviceModelId:resource.deviceModelId,deviceInstanceId:resource.deviceInstanceId,targetName:'',regionName:''})}
function resourceLabel(resource:any){return `${resource.flowName||resource.flowModelId} / ${resource.nodeName} → ${resource.instanceName||('实例'+(resource.deviceInstanceId||'待绑定'))}`}
function nodesFor(flowId:any){const nodes=props.taskMode?props.taskWorkflowNodes.filter((x:any)=>Number(x.flowModelId)===Number(flowId)):props.workflows.find((x:any)=>Number(x.id)===Number(flowId))?.nodesDef||[];return [...new Map(nodes.map((node:any)=>[node.name,node])).values()]}
function addAction(){form.actions.push(newAction())}function resetAction(item:any){Object.assign(item,{action:'ALERT',targetTaskId:null,resourceKey:'',deviceModelId:null,deviceInstanceId:null,capabilityName:'',parameters:{}})}function resetActionDevice(item:any){Object.assign(item,{deviceInstanceId:null,capabilityName:'',parameters:{}})}function selectActionResource(item:any){const resource=props.taskResources.find((x:any)=>x.bindingKey===item.resourceKey);if(resource)Object.assign(item,{deviceModelId:resource.deviceModelId,deviceInstanceId:resource.deviceInstanceId,capabilityName:'',parameters:{}})}
function parameterDefinitions(item:any){const capability=capabilitiesFor(item.deviceModelId).find((x:any)=>x.capabilityName===item.capabilityName);const raw=capability?.capabilityParameters||capability?.parameters;if(Array.isArray(raw))return raw.map((x:any)=>({name:x.parameterName||x.name,dataType:x.dataType||'STRING'}));if(raw&&typeof raw==='object')return Object.entries(raw).map(([name,value]:any)=>({name,dataType:value?.dataType||'STRING'}));return []}
function initParameters(item:any){item.parameters={};parameterDefinitions(item).forEach((x:any)=>item.parameters[x.name]=x.dataType==='BOOLEAN'?false:'')}
function bindingPayload(item:any){if(item.bindingType==='LITERAL'){if(item.value===null||item.value===undefined||item.value==='')throw Error(`@${item.name}缺少固定值`);return{bindingType:'LITERAL',value:item.value}}const resolvedDataType=observableDataType(item);if(!scalarTypes.includes(resolvedDataType))throw Error(`@${item.name}缺少可求值的数据类型`);const source:any={sourceType:item.sourceType,dataType:resolvedDataType};if(isDeviceSource(item.sourceType)){if(!item.deviceModelId)throw Error(`@${item.name}缺少设备模型`);if(props.taskMode&&!item.deviceInstanceId)throw Error(`@${item.name}必须选择任务设备`);source.deviceModelId=item.deviceModelId;if(item.deviceInstanceId)source.deviceInstanceId=item.deviceInstanceId;if(item.sourceType==='DEVICE_ATTRIBUTE'){if(!item.targetName)throw Error(`@${item.name}缺少设备属性`);source.targetName=item.targetName}if(item.sourceType==='DEVICE_OPERATION_STATE'){if(!item.regionName)throw Error(`@${item.name}缺少OP状态空间`);source.regionName=item.regionName}}else if(isNodeSource(item.sourceType)){if(!item.workflowTemplateId||!item.nodeName)throw Error(`@${item.name}缺少工作流节点`);source.workflowTemplateId=item.workflowTemplateId;source.nodeName=item.nodeName;if(item.sourceType==='NODE_INTERNAL_VARIABLE'){if(!item.variableName)throw Error(`@${item.name}缺少内部变量`);source.variableName=item.variableName}}else if(!props.taskMode){if(!item.taskId)throw Error(`@${item.name}缺少目标任务`);source.taskId=item.taskId}return{bindingType:'OBSERVABLE',source}}
function actionPayload(item:any){if(item.actionType==='SYSTEM'){if(!props.taskMode&&item.action!=='ALERT'&&!item.targetTaskId)throw Error(`${item.action}必须选择目标任务`);return{actionType:'SYSTEM',action:item.action,targetTaskId:props.taskMode?null:(item.action==='ALERT'?null:item.targetTaskId)}}if(!item.deviceInstanceId||!item.capabilityName)throw Error('设备能力动作必须选择实例和能力');return{actionType:'DEVICE_CAPABILITY',deviceInstanceId:item.deviceInstanceId,capabilityName:item.capabilityName,parameters:item.parameters}}
function validateAndBuild(){if(!form.ruleName.trim())throw Error('请输入规则名称');validateDisplayExpressionSyntax(form.displayExpression);if(!backendExpression.value)throw Error('请输入违规表达式');if(!variableNames().length)throw Error('表达式至少需要一个@变量引用');const bindings:any={};for(const item of form.bindings)bindings[item.name]=bindingPayload(item);if(!form.actions.length)throw Error('请至少配置一个违规动作');return{ruleName:form.ruleName.trim(),description:form.description.trim(),expression:backendExpression.value,bindings,windowSeconds:form.windowSeconds||null,violationActions:form.actions.map(actionPayload),isEnabled:form.isEnabled}}
function displayExpression(rule:any){let expression=rule?.expression||'';for(const name of Object.keys(rule?.bindings||{}).sort((a,b)=>b.length-a.length))expression=expression.replace(new RegExp(`\\b${name}\\b`,'g'),`@${name}`);return expression}
function loadRule(rule?:any){Object.assign(form,{ruleName:rule?.ruleName||'',description:rule?.description||'',isEnabled:rule?.isEnabled!==false,displayExpression:displayExpression(rule),bindings:[],actions:[newAction()],windowSeconds:rule?.windowSeconds??null});form.bindings=Object.entries(rule?.bindings||{}).map(([name,binding]:any)=>{const source=binding.source||{};const resource=props.taskResources.find((x:any)=>Number(x.deviceInstanceId)===Number(source.deviceInstanceId));return{...newBinding(name),name,bindingType:binding.bindingType||'OBSERVABLE',value:binding.value,dataType:source.dataType||(typeof binding.value==='boolean'?'BOOLEAN':'DOUBLE'),sourceType:source.sourceType||'DEVICE_ATTRIBUTE',resourceKey:resource?.bindingKey||'',deviceModelId:source.deviceModelId||null,deviceInstanceId:source.deviceInstanceId||null,targetName:source.targetName||'',regionName:source.regionName||'',workflowTemplateId:source.workflowTemplateId||null,nodeName:source.nodeName||'',variableName:source.variableName||'',taskId:source.taskId||null}});form.actions=(rule?.violationActions||[]).map((action:any)=>{const resource=props.taskResources.find((x:any)=>Number(x.deviceInstanceId)===Number(action.deviceInstanceId));const instance=props.instances.find((x:any)=>Number(x.id)===Number(action.deviceInstanceId));return{...newAction(),actionType:action.actionType||'SYSTEM',action:action.action||'ALERT',targetTaskId:action.targetTaskId||null,resourceKey:resource?.bindingKey||'',deviceModelId:resource?.deviceModelId||instance?.deviceModelId||instance?.modelId||null,deviceInstanceId:action.deviceInstanceId||null,capabilityName:action.capabilityName||'',parameters:action.parameters||{}}});if(!form.actions.length)form.actions=[newAction()];syncBindings()}
loadRule()
defineExpose({validateAndBuild,loadRule})
</script>

<style scoped>
.constraint-editor{display:grid;gap:14px}.editor-block{padding:14px;border:1px solid #dbe4ef;border-radius:6px;background:#fafcff}.block-head,.block-head>div,.entry-title{display:flex;align-items:center;justify-content:space-between;gap:10px}.block-head>div{align-items:flex-start;flex-direction:column;gap:3px}.block-head span,.inline-hint,.formula-help{color:#64748b;font-size:12px}.formula-input{margin-top:12px}.formula-input :deep(.el-input__inner),code{font-family:Consolas,monospace;color:#1d4ed8}.formula-help{margin-top:7px}.formula-panel{display:grid;grid-template-columns:1fr 1fr;gap:8px}.formula-panel-title{grid-column:1/-1;font-weight:600;margin-bottom:4px}.formula-panel button{display:grid;gap:5px;padding:10px;border:1px solid #dbe4ef;border-radius:5px;background:#fff;text-align:left;cursor:pointer}.formula-panel button:hover{border-color:#2563eb;background:#eff6ff}.formula-panel span{color:#64748b;font-size:11px}.entry{margin-top:10px;padding:12px;border:1px solid #e1e8f0;border-radius:5px;background:#fff}.entry-title{margin-bottom:10px}
</style>


